export const GET_STREAMS_START = 'GET_STREAMS_START';
export const GET_STREAMS_SUCCESS = 'GET_STREAMS_SUCCESS';
export const GET_STREAMS_FAIL = 'GET_STREAMS_FAIL';

export const GET_GAMES_START = 'GET_GAMES_START';
export const GET_GAMES_SUCCESS = 'GET_GAMES_SUCCESS';
export const GET_GAMES_FAIL = 'GET_GAMES_FAIL';

export const GET_CHANNELS_START = 'GET_CHANNELS_START';
export const GET_CHANNELS_SUCCESS = 'GET_CHANNELS_SUCCESS';
export const GET_CHANNELS_FAIL = 'GET_CHANNELS_FAIL';

export const ADD_CHANNEL_TO_FAVORITES_START = 'ADD_CHANNEL_TO_FAVORITES_START';
export const ADD_CHANNEL_TO_FAVORITES_SUCCESS = 'ADD_CHANNEL_TO_FAVORITES_SUCCESS';
export const ADD_CHANNEL_TO_FAVORITES_FAIL = 'ADD_CHANNEL_TO_FAVORITES_FAIL';
